### ISSUE TITLE
Publish to Pypi workflow

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/carrot-transform#1]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We would like this app to be published to Pypi

### Acceptance Criteria

- [x] Carrot transform is available on pypi

### Tasks

- [x] Github workflow (trigger on release)
- [x] Necessary code changes ?
- [x] Pypi auth / github settings

### Confirm creation

- [x] This issue is ready
