### ISSUE TITLE
Transform Documentation

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/carrot-transform#2]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We need to add docs for Carrot Transform to carrot4omop.ac.uk

### Acceptance Criteria

- [ ] Documentation exists

### Tasks

- [x] Add section to the docs site
- [ ] Move anything from CDM that is relevant
- [x] Update / write anything necessary (CLI)

### Confirm creation

- [x] This issue is ready

**Comment by AndyRae** [comment]
https://github.com/Health-Informatics-UoN/carrot-docs

Old docs including Carrot-CDM
