### ISSUE TITLE
Write test output comparitor

### ISSUE THREAD

**Issue by anwarfg** [Health-Informatics-UoN/carrot-transform#3]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Write a test to compare outputs of carrot transform with outputs from carrot cdm.

### Acceptance Criteria

- [ ] Tests exist.
- [ ] Tests validated.

### Tasks

- [ ] compare headers between files
- [ ] compare data between two files. Note that the data may not be in the same order.
- [ ] Unit tests.
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
